---
- name: Create installation root
  file:
    path: "{{ rasputin_cfg_root }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  tags: config

- name: Template config files
  template:
    dest: "{{ rasputin_cfg_root }}/{{ item.path }}"
    src: "{{ item.path }}"
    owner: '{{ item.owner | default("root") }}'
    group: root
    mode: "0600"
  loop:
    - path: docker-compose.yml
    - path: registry.yml
  tags: config

- name: Create system users
  include_tasks: system-user.yml
  loop:
    - user: "{{ minio_user }}"
      group: "{{ minio_group }}"

- name: Create data directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(1000) }}"
    group: "{{ item.group | default(1000) }}"
    mode: '{{ item.mode | default("0755") }}'
  loop:
    - path: "{{ rasputin_pihole_root }}"
      owner: root
      group: root
    - path: "{{ minio_data_dir }}"
      owner: "{{ minio_user }}"
      group: "{{ minio_group }}"
    - path: "{{ rasputin_data_root }}/transmission"
      owner: "{{ minio_user }}"
      group: "{{ minio_group }}"
    - path: "{{ rasputin_data_root }}/torrents"
      owner: "{{ minio_user }}"
      group: "{{ minio_group }}"
    - path: "{{ rasputin_data_root }}/plex"
    - path: "{{ rasputin_data_root }}/media"
    - path: "{{ rasputin_vaultwarden_root }}"
      owner: root
      group: root
      mode: "0750"
  tags: config

- import_tasks: certificates.yml
  tags: certs
- import_tasks: minio.yml
  tags: minio
- import_tasks: haproxy.yml
  tags: haproxy

- name: Start services
  command:
    cmd: docker-compose up -d
    chdir: "{{ rasputin_cfg_root }}"
