---
version: "0.1"

http:
  addr: "0.0.0.0:5000"
  host: "https://{{ registry_url }}"

storage:
  s3:
    accesskey: "{{ registry_s3_accesskey }}"
    secretkey: "{{ registry_s3_secretkey }}"
    bucket: "{{ registry_s3_bucket }}"
    region: "{{ registry_s3_region }}"
    regionendpoint: "{{ registry_s3_endpoint }}"
  cache:
    blobdescriptor: inmemory

proxy:
  remoteurl: "https://registry-1.docker.io"
  username: "{{ registry_upstream_username }}"
  password: "{{ registry_upstream_password }}"
