---
- name: reload haproxy
  service:
    name: haproxy
    state: reloaded

- name: update certificates
  command: /etc/letsencrypt/renewal-hooks/deploy/rasputin.sh

- name: restart minio
  ansible.builtin.systemd:
    name: minio
    state: restarted
    daemon_reload: yes

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes
