---
rasputin_cfg_root: /opt/rasputin
rasputin_data_root: /srv
rasputin_pki_root: /etc/pki

# Pi-hole
rasputin_pihole_root: "{{ rasputin_data_root }}/pihole"
rasputin_pihole_upstream_dns2: "no"

# Registry
registry_url: "registry.{{ rasputin_domain }}"
registry_port: 5000
registry_s3_endpoint: "https://{{ minio_server_url }}"

# MinIO
minio_server_url: objects.{{ rasputin_domain }}
minio_console_url: minio.{{ rasputin_domain }}
minio_server_port: 9000
minio_console_port: 9001
# renovate: depName=minio/minio
minio_version: RELEASE.2022-07-17T15-43-14Z
minio_data_dir: "{{ rasputin_data_root }}/minio"
minio_user: minio
minio_group: minio

# Bitwarden
rasputin_vaultwarden_root: "{{ rasputin_data_root }}/vaultwarden"
