---
rasputin_cfg_root: /opt/rasputin
rasputin_data_root: /srv
rasputin_pki_root: /etc/pki

# Pi-hole
rasputin_pihole_root: "{{ rasputin_data_root }}/pihole"
rasputin_pihole_upstream_dns2: "no"

# Registry
registry_url: "registry.{{ rasputin_domain }}"
registry_port: 5000
registry_s3_endpoint: "https://{{ minio_server_url }}"

# MinIO
minio_server_url: objects.{{ rasputin_domain }}
minio_console_url: minio.{{ rasputin_domain }}
minio_server_port: 9000
minio_console_port: 9001
# renovate: depName=minio/minio
minio_version: RELEASE.2022-01-03T18-22-58Z
minio_data_dir: "{{ rasputin_data_root }}/minio"
minio_user: minio
minio_group: minio

# Bitwarden
rasputin_vaultwarden_root: "{{ rasputin_data_root }}/vaultwarden"

# Prometheus
# renovate: depName=prometheus/prometheus
prometheus_version: v2.32.1
prometheus_version_no_v: "{{ prometheus_version | replace('v', '') }}"
prometheus_url: "prometheus.{{ rasputin_domain }}"
prometheus_port: 9090
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_data_dir: "{{ rasputin_data_root }}/prometheus"
prometheus_config_dir: /etc/prometheus
prometheus_archive: "prometheus-{{ prometheus_version_no_v }}.linux-armv7.tar.gz"
prometheus_retention_time: 365d

# renovate: depName=prometheus/node_exporter
node_exporter_version: v1.3.1
node_exporter_version_no_v: "{{ node_exporter_version | replace('v', '') }}"
node_exporter_port: 9100
node_exporter_archive: "node_exporter-{{ node_exporter_version_no_v }}.linux-armv7.tar.gz"
node_exporter_enabled_collectors: []
node_exporter_disabled_collectors:
  - nfs
  - nfsd
