---
rasputin_cfg_root: /opt/rasputin
rasputin_data_root: /srv
rasputin_pki_root: /etc/pki

# Pi-hole
rasputin_pihole_root: "{{ rasputin_data_root }}/pihole"
rasputin_pihole_upstream_dns2: "no"

# Registry
registry_url: "registry.{{ rasputin_domain }}"
registry_port: 5000
registry_s3_endpoint: "https://{{ minio_server_url }}"

# MinIO
minio_server_url: objects.{{ rasputin_domain }}
minio_console_url: minio.{{ rasputin_domain }}
minio_server_port: 9000
minio_console_port: 9001
# renovate: depName=minio/minio
minio_version: RELEASE.2022-12-12T19-27-27Z
minio_data_dir: "{{ rasputin_data_root }}/minio"
minio_user: minio
minio_group: minio

# Bitwarden
rasputin_vaultwarden_root: "{{ rasputin_data_root }}/vaultwarden"

# Vault
# renovate: depName=hashicorp/vault
vault_version: v1.13.0
vault_version_no_v: "{{ vault_version | replace('v', '') }}"
vault_archive: "vault_{{ vault_version_no_v }}_linux_arm.zip"
vault_download_url: "https://releases.hashicorp.com/vault/{{ vault_version_no_v }}/{{ vault_archive }}"
vault_checksums_url: "https://releases.hashicorp.com/vault/{{ vault_version_no_v }}/vault_{{ vault_version_no_v }}_SHA256SUMS"
vault_config_path: /etc/vault.hcl
vault_user: vault
vault_group: vault
vault_port: 8200
vault_cluster_port: 8201
vault_raft_path: "{{ rasputin_data_root }}/vault"
