---
rasputin_cfg_root: /opt/rasputin
rasputin_data_root: /srv
rasputin_pki_root: /etc/pki

# Pi-hole
rasputin_pihole_root: "{{ rasputin_data_root }}/pihole"
rasputin_pihole_upstream_dns2: "no"

# Registry
registry_url: "registry.{{ rasputin_domain }}"
registry_port: 5000
registry_s3_endpoint: "https://{{ minio_server_url }}"

# MinIO
minio_server_url: objects.{{ rasputin_domain }}
minio_console_url: minio.{{ rasputin_domain }}
minio_server_port: 9000
minio_console_port: 9001
# renovate: datasource=github-tags depName=minio/minio
minio_version: RELEASE.2021-12-10T23-03-39Z
minio_data_dir: "{{ rasputin_data_root }}/minio"
minio_user: minio
minio_group: minio

# Bitwarden
rasputin_vaultwarden_root: "{{ rasputin_data_root }}/vaultwarden"

# Prometheus
prometheus_version: "2.31.1"
prometheus_url: "prometheus.{{ rasputin_domain }}"
prometheus_port: 9090
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_data_dir: "{{ rasputin_data_root }}/prometheus"
prometheus_config_dir: /etc/prometheus
prometheus_archive: "prometheus-{{ prometheus_version }}.linux-armv7.tar.gz"
prometheus_retention_time: 365d

node_exporter_version: "1.3.1"
node_exporter_port: 9100
node_exporter_archive: "node_exporter-{{ node_exporter_version }}.linux-armv7.tar.gz"
node_exporter_enabled_collectors: []
node_exporter_disabled_collectors: []
